#!/usr/bin/python3
from sys import argv

def fact(n):
    i = 2

    if n < 2:
        return

    while n % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(n, n / i, i))


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            num = int(line.split('\n')[0])
            fact(num)
            line = file.readline()
except:
    pass
